services:
  # Test environment services
  _defaults:
    autowire: true
    autoconfigure: true
    public: true

  # DataFixtures services for test environment
  ServerCommandBundle\DataFixtures\:
    resource: '../../DataFixtures/'